-- -- This file is automatically loaded by plugins.core
-- vim.g.mapleader = " "
-- vim.g.maplocalleader = "\\"
--
-- -- LazyVim auto format
-- vim.g.autoformat = true
--
-- -- Snacks animations
-- -- Set to `false` to globally disable all snacks animations
vim.g.snacks_animate = false
--
-- -- LazyVim picker to use.
-- -- Can be one of: telescope, fzf
-- -- Leave it to "auto" to automatically use the picker
-- -- enabled with `:LazyExtras`
-- vim.g.lazyvim_picker = "auto"
--
-- -- LazyVim completion engine to use.
-- -- Can be one of: nvim-cmp, blink.cmp
-- -- Leave it to "auto" to automatically use the completion engine
-- -- enabled with `:LazyExtras`
-- vim.g.lazyvim_cmp = "auto"
--
-- -- if the completion engine supports the AI source,
-- -- use that instead of inline suggestions
-- vim.g.ai_cmp = true
--
-- -- LazyVim root dir detection
-- -- Each entry can be:
-- -- * the name of a detector function like `lsp` or `cwd`
-- -- * a pattern or array of patterns like `.git` or `lua`.
-- -- * a function with signature `function(buf) -> string|string[]`
-- vim.g.root_spec = { "lsp", { ".git", "lua" }, "cwd" }
--
-- -- Optionally setup the terminal to use
-- -- This sets `vim.o.shell` and does some additional configuration for:
-- -- * pwsh
-- -- * powershell
-- -- LazyVim.terminal.setup("pwsh")
--
-- -- Set LSP servers to be ignored when used with `util.root.detectors.lsp`
-- -- for detecting the LSP root
-- vim.g.root_lsp_ignore = { "copilot" }
--
-- -- Hide deprecation warnings
-- vim.g.deprecation_warnings = false
--
-- -- Show the current document symbols location from Trouble in lualine
-- -- You can disable this for a buffer by setting `vim.b.trouble_lualine = false`
-- vim.g.trouble_lualine = true
